/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;


public class ManagerloginForm extends ActionForm {
	private String password;

	private String account;

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
	
		return null;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
		
	}

	
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	
	public String getAccount() {
		return account;
	}


	public void setAccount(String account) {
		this.account = account;
	}
}