/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Customer;
import po.Tz;

import com.yourcompany.struts.form.AlterForm;
import com.yourcompany.struts.form.AltertzForm;

import dao.IManagerDao;


public class AddtzAction extends Action {
	private IManagerDao mdao;	

	
	public IManagerDao getMdao() {
		return mdao;
	}


	public void setMdao(IManagerDao mdao) {
		this.mdao = mdao;
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AltertzForm altertzForm = (AltertzForm) form;
		String name=altertzForm.getName();
		String status=altertzForm.getStatus();
		String office=altertzForm.getOffice();
		String date=altertzForm.getDate();
		double price=altertzForm.getPrice();
		
		Tz tz=new Tz();
		
		tz.setName(name);
		tz.setStatus(status);
		tz.setOffice(office);
		tz.setDate(date);
		tz.setPrice(price);
		
		mdao.insertTz(tz);
		ArrayList tzlist=(ArrayList)mdao.getTzlist();
		request.getSession().setAttribute("tzlist",tzlist);
		return new ActionForward("/manager-tz.jsp");
	}
}
	