/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dao.ICustomerDao;


public class AgreeAction extends Action {
private ICustomerDao cdao;
	public ICustomerDao getCdao() {
		return cdao;
	}

	public void setCdao(ICustomerDao cdao) {
		this.cdao = cdao;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String sender=new String(request.getParameter("sender")); 
		String sendername=new String(request.getParameter("sendername")); 
		String receiver=new String(request.getParameter("receiver")); 
		String receivername=new String(request.getParameter("receivername")); 
		cdao.agree(sender, receiver, sendername, receivername);
		ArrayList applylist=cdao.getApplyByAccount(receiver);
		ArrayList friendlist=cdao.getFriendByAccount(receiver);
		request.getSession().setAttribute("applylist", applylist);
		request.getSession().setAttribute("friendlist", friendlist);
		return new ActionForward("/menu.jsp");
	}
}