/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Apply;
import dao.ICustomerDao;


public class ApplyAction extends Action {
	private ICustomerDao cdao;
	public ICustomerDao getCdao() {
		return cdao;
	}

	public void setCdao(ICustomerDao cdao) {
		this.cdao = cdao;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Date date = new Date();
		SimpleDateFormat dateFormat= new SimpleDateFormat("yyyy-MM-dd :HH:mm:ss");
		String sender=new String(request.getParameter("sender")); 
		String sendername=new String(request.getParameter("sendername")); 
		String receiver=new String(request.getParameter("receiver")); 
		String message=new String(request.getParameter("message")); 
		String time=dateFormat.format(date);
		
		Apply apply=new Apply();
		apply.setSender(sender);
		apply.setMessage(message);
		apply.setReceiver(receiver);
		apply.setTime(time);
		apply.setSendername(sendername);
		apply.setAgree(0);
		
		cdao.insertApply(apply);
		return new ActionForward("/menu.jsp");

	}
}