/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;

import po.Actz;
import po.Customer;

import com.yourcompany.struts.form.BuyForm;

import dao.ICustomerDao;

public class BuyAction extends Action {
private ICustomerDao cdao;
	
	public ICustomerDao getCdao() {
		return cdao;
	}

	public void setCdao(ICustomerDao cdao) {
		this.cdao = cdao;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BuyForm buyForm = (BuyForm) form;// TODO Auto-generated method stub
		Customer cus = (Customer)request.getSession().getAttribute("cus1");
		String account=cus.getAccount();
		String office = buyForm.getOffice();
		String name = buyForm.getName();
		String status = buyForm.getStatus();
		String date = buyForm.getDate();
		double price=buyForm.getPrice();
		
		ActionMessages errors = new ActionMessages();
		
		ArrayList list2 = (ArrayList)cdao.getActzByAccount(account);
		Actz ac=new Actz();
		for(int i=0;i<list2.size();i++){
			ac=(Actz)list2.get(i);
			if(ac.getOffice().equals(office)){
				System.out.println(ac.getOffice());
				return new ActionForward("/error2.jsp");
			}
		}
		
		
		if(cus.getCbalance()<price){
			return new ActionForward("/error.jsp");
		}	
		
		System.out.println(price+"price");
		
		cus.setCbalance(cus.getCbalance() - price);
		cdao.updateCustomer(cus);
		cdao.insertMx(account, "-", price);
		ArrayList list = (ArrayList)cdao.getMxByAccount(account);
		request.getSession().setAttribute("list", list);
		Actz actz=new Actz();
		actz.setAccount(account);
		actz.setDate(date);
		actz.setName(name);
		actz.setPrice(price);
		actz.setStatus(status);
		actz.setOffice(office);
		cdao.insertActz(actz);
		ArrayList list5 = (ArrayList)cdao.getActzByAccount(account);
		request.getSession().setAttribute("list5", list5);
		return new ActionForward("/menu.jsp");
	}
}