/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dao.CustomerDao;
import dao.ICustomerDao;


public class ChatAction extends Action {
	private ICustomerDao cdao;
	public ICustomerDao getCdao() {
		return cdao;
	}

	public void setCdao(ICustomerDao cdao) {
		this.cdao = cdao;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		  String account=new String(request.getParameter("account")); 
		  String friendaccount=new String(request.getParameter("friendaccount")); 
		  String friendname=new String(request.getParameter("friendname")); 
		  System.out.println(account+friendaccount);
		  ArrayList chatlist=cdao.getChatByAccount(account, friendaccount);
		  System.out.println(chatlist.size()+"123");
		  request.getSession().setAttribute("friendaccount", friendaccount);
		  request.getSession().setAttribute("friendname", friendname);
		  request.getSession().setAttribute("chatlist", chatlist);
		  return new ActionForward("/chat.jsp");
	}
}