/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Customer;
import po.Mx;

import com.yourcompany.struts.form.CunkuanForm;

import dao.CustomerDao;
import dao.ICustomerDao;

public class CunkuanAction extends Action {
private ICustomerDao cdao;
	
	public ICustomerDao getCdao() {
		return cdao;
	}

	public void setCdao(ICustomerDao cdao) {
		this.cdao = cdao;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		CunkuanForm cunkuanForm = (CunkuanForm) form;// TODO Auto-generated method stub
		String str = cunkuanForm.getMoney(),account;
		double money = Double.parseDouble(str);
		
		Customer cus = (Customer)request.getSession().getAttribute("cus1");
		cus.setCbalance(cus.getCbalance() + money);
		account=cus.getAccount();
		cdao.updateCustomer(cus);
		cdao.insertMx(account, "+", money);
		ArrayList list = (ArrayList)cdao.getMxByAccount(account);
		request.getSession().setAttribute("list", list);
		Mx m=(Mx)list.get(0);
		System.out.println(m.getTime()+"yy");
		return new ActionForward("/menu.jsp");
	}
}