/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import po.Customer;
import com.yourcompany.struts.form.LoginForm;
import dao.ICustomerDao;

public class LoginAction extends Action {
	private ICustomerDao cdao;
	
	public ICustomerDao getCdao() {
		return cdao;
	}

	public void setCdao(ICustomerDao cdao) {
		this.cdao = cdao;
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		String account = loginForm.getAccount();
		String password = loginForm.getPassword();
		Customer cus1 = null;
		ArrayList list=cdao.getMxByAccount(account);
		ArrayList list2=cdao.getZzhkByAccount1(account);
		ArrayList list3=cdao.getZzhkByAccount2(account);
		ArrayList list4=cdao.getTz();
		ArrayList list5=cdao.getActzByAccount(account);
		ArrayList newlist=cdao.getNew();
		ArrayList applylist=cdao.getApplyByAccount(account);
		ArrayList friendlist=cdao.getFriendByAccount(account);
		cus1 = cdao.getCustomerByAccount(account);
		Customer searchcustomer=new Customer();
		searchcustomer.setAccount(null);
		searchcustomer.setPassword(null);
		searchcustomer.setCname(null);
		searchcustomer.setEmail(null);
		searchcustomer.setCbalance(0);
		
		ActionMessages errors = new ActionMessages();
		if(cus1==null || !(cus1.getPassword().toString().equals(String.valueOf(password)))){
			if(cus1==null)
				System.out.println("cus1==null");
			if( !(cus1.getPassword().toString().equals(String.valueOf(password))))
				System.out.println( !(cus1.getPassword().toString().equals(String.valueOf(password))));
			System.out.println("用户名或密码错误");
			return new ActionForward("/login.jsp");
		}
		request.getSession().setAttribute("cus1", cus1);
		request.getSession().setAttribute("list", list);
		request.getSession().setAttribute("list2", list2);
		request.getSession().setAttribute("list3", list3);
		request.getSession().setAttribute("list4", list4);
		request.getSession().setAttribute("list5", list5);
		request.getSession().setAttribute("newlist", newlist);
		request.getSession().setAttribute("applylist", applylist);
		request.getSession().setAttribute("searchcustomer", searchcustomer);
		request.getSession().setAttribute("friendlist", friendlist);
		System.out.println(list4.size());
		
		return new ActionForward("/menu.jsp");
	}
}