/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import po.Customer;
import po.Manager;
import po.Tz;

import com.yourcompany.struts.form.ManagerloginForm;

import dao.IManagerDao;


public class ManagerloginAction extends Action {
	private IManagerDao mdao;
	
	public IManagerDao getMdao() {
		return mdao;
	}

	public void setMdao(IManagerDao mdao) {
		this.mdao = mdao;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ManagerloginForm managerloginForm = (ManagerloginForm) form;// TODO Auto-generated method stub
		String account = managerloginForm.getAccount();
		String password = managerloginForm.getPassword();
		Manager manager=(Manager)mdao.getManagerByAccount(account);
		ArrayList customerlist=(ArrayList)mdao.getCustomerlist();
		ArrayList tzlist=(ArrayList)mdao.getTzlist();
		Customer customer=new Customer();
		customer.setAccount(null);
		customer.setPassword(null);
		customer.setCname(null);
		customer.setEmail(null);
		customer.setCbalance(0);
		
		
		ActionMessages errors = new ActionMessages();
		if(manager==null || !(manager.getPassword().toString().equals(String.valueOf(password)))){
			if(manager==null)
				System.out.println("cus1==null");
			if( !(manager.getPassword().toString().equals(String.valueOf(password))))
				System.out.println( !(manager.getPassword().toString().equals(String.valueOf(password))));
			System.out.println("用户名或密码错误");
			return new ActionForward("/managerlogin.jsp");
		}
		request.getSession().setAttribute("manager", manager);
		request.getSession().setAttribute("customerlist", customerlist);
		request.getSession().setAttribute("tzlist", tzlist);
		request.getSession().setAttribute("searchcustomer", customer);
		return new ActionForward("/searchmenu.jsp");
	}
}