/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;



import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import po.Customer;

import com.yourcompany.struts.form.QukuanForm;

import dao.CustomerDao;
import dao.ICustomerDao;


public class QukuanAction extends Action {
private ICustomerDao cdao;
	
	public ICustomerDao getCdao() {
		return cdao;
	}

	public void setCdao(ICustomerDao cdao) {
		this.cdao = cdao;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		QukuanForm qukuanForm = (QukuanForm) form;// TODO Auto-generated method stub
		
		String str = qukuanForm.getMoney(),account;
		double money = Double.parseDouble(str);
		
		Customer cus = (Customer)request.getSession().getAttribute("cus1");
		ActionMessages errors = new ActionMessages();
		if(cus.getCbalance()<money){
			return new ActionForward("/error.jsp");
		}	
		
		cus.setCbalance(cus.getCbalance() - money);
		account=cus.getAccount();
		cdao.updateCustomer(cus);
		cdao.insertMx(account, "-", money);
		ArrayList list = (ArrayList)cdao.getMxByAccount(account);
		request.getSession().setAttribute("list", list);
		return new ActionForward("/menu.jsp");

	}
}