/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import po.Customer;

import com.yourcompany.struts.form.RegisterForm;

import dao.CustomerDao;
import dao.ICustomerDao;

public class RegisterAction extends Action {
private ICustomerDao cdao;
	
	public ICustomerDao getCdao() {
		return cdao;
	}

	public void setCdao(ICustomerDao cdao) {
		this.cdao = cdao;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegisterForm registerForm = (RegisterForm) form;// TODO Auto-generated method stub
		String account = registerForm.getAccount();
		String password = registerForm.getPassword();
		String cname = registerForm.getCname();
		String email = registerForm.getEmail();
		Customer cus=cdao.getCustomerByAccount(account);
		
		ActionMessages errors = new ActionMessages();
		if(cus!=null){
			ActionMessage error = new ActionMessage("error.register",account);
			errors.add("register",error);
			this.saveErrors(request, errors);
			return mapping.getInputForward();
		}
		
		cus = new Customer();
		cus.setAccount(account);
		cus.setPassword(password);
		cus.setCname(cname);
		cus.setCbalance(0);
		cus.setEmail(email);
		cdao.insertCustomer(cus);
		cdao.insertMx(account,"null",0);
		
		return new ActionForward("/login.jsp");
	}
}