/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Actz;
import po.Customer;

import com.yourcompany.struts.form.SaleForm;

import dao.ICustomerDao;


public class SaleAction extends Action {
private ICustomerDao cdao;
	
	public ICustomerDao getCdao() {
		return cdao;
	}

	public void setCdao(ICustomerDao cdao) {
		this.cdao = cdao;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SaleForm saleForm = (SaleForm) form;
		Customer cus = (Customer)request.getSession().getAttribute("cus1");
		String account=cus.getAccount();
		String office = saleForm.getOffice();
		double price=saleForm.getPrice();
		
		System.out.println(price+"pp");
		
		Map map=new HashMap();
		map.put("account", account);
		map.put("office", office);
		cdao.deleteActz(map);
		
		cus.setCbalance(cus.getCbalance() + price);
		cdao.updateCustomer(cus);
		cdao.insertMx(account, "+", price);
		ArrayList list = (ArrayList)cdao.getMxByAccount(account);
		request.getSession().setAttribute("list", list);
		ArrayList list5 = (ArrayList)cdao.getActzByAccount(account);
		request.getSession().setAttribute("list5", list5);
		return new ActionForward("/menu.jsp");
	}
}