/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Chat;
import dao.ICustomerDao;


public class SendmessageAction extends Action {
	private ICustomerDao cdao;
	public ICustomerDao getCdao() {
		return cdao;
	}

	public void setCdao(ICustomerDao cdao) {
		this.cdao = cdao;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		 Date date = new Date();
		 SimpleDateFormat dateFormat= new SimpleDateFormat("yyyy-MM-dd :HH:mm:ss");
		 String text=new String(request.getParameter("text")); 
		 String senderaccount=new String(request.getParameter("senderaccount")); 
		 String receiveraccount=new String(request.getParameter("receiveraccount")); 
		 String time=dateFormat.format(date);
		 System.out.println(text);
		 
		 Chat chat=new Chat();
		 chat.setSenderaccount(senderaccount);
		 chat.setReceiveraccount(receiveraccount);
		 chat.setText(text);
		 chat.setTime(time);
		 
		 cdao.insertChat(chat);
		 ArrayList chatlist=(ArrayList)cdao.getChatByAccount(senderaccount, receiveraccount);
		
		 request.getSession().setAttribute("chatlist", chatlist);
		 return new ActionForward("/chat.jsp");
	}
}