/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import po.Customer;
import po.Mx;

import com.yourcompany.struts.form.ZzhkForm;

import dao.ICustomerDao;

public class ZzhkAction extends Action {
	private ICustomerDao cdao;
	
	public ICustomerDao getCdao() {
		return cdao;
	}

	public void setCdao(ICustomerDao cdao) {
		this.cdao = cdao;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ZzhkForm zzhkForm = (ZzhkForm) form;// TODO Auto-generated method stub
		String account1 = zzhkForm.getAccount(),mo=zzhkForm.getMoney(),account2;
		double money = Double.parseDouble(mo);
		
		Customer cus = (Customer)request.getSession().getAttribute("cus1");
		account2=cus.getAccount();//得到转出账户的account
		
		cus.setCbalance(cus.getCbalance() - money);
		
		Customer cus2=(Customer)cdao.getCustomerByAccount(account1);//得到被转入账户的po
		cus2.setCbalance(cus2.getCbalance()+money);
		
		cdao.updateCustomer(cus);
		cdao.updateCustomer(cus2);
		
		cdao.insertMx(account2, "-", money);
		cdao.insertMx(account1, "+", money);
		cdao.insertZzhk(account2, account1, money);
		ArrayList list = (ArrayList)cdao.getMxByAccount(account2);
		request.getSession().setAttribute("list", list);
		ArrayList list2 = (ArrayList)cdao.getZzhkByAccount1(account2);
		request.getSession().setAttribute("list2", list2);
		Mx m=(Mx)list.get(0);
		System.out.println(m.getTime()+"yy");
		return new ActionForward("/zzhk.jsp");
	}
}